# Generated by Django 4.0.1 on 2022-01-31 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=1000)),
                ('comment', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=200)),
                ('ts_created', models.DateTimeField(default=datetime.datetime.now)),
                ('ts_schedule', models.DateTimeField()),
            ],
        ),
    ]
